### ISSUE TITLE
create site of harmonic

### ISSUE THREAD

**Issue by mateusortiz** [JSRocksHQ/harmonic#101]
Think it would be cool and interactive the site of harmonic, with documentation, introduction of installing and showing any project.

Example DocPad documentation. :smile:

**Comment by randsonjs** [comment]
+1 for this!

The website of DocPad it's so cool! :smile:

**Comment by joridos** [comment]
:+1: good idea, we have this http://es6rocks.com/harmonic/ but with small informations.
One site with docs, get started and much more is awesome, something like this http://yeoman.io/

**Comment by mateusortiz** [comment]
I'm still working on it, but now to discuss some topics.

first that I am not a designer, just trying to help, we can change everything if you think differently :D

First mockup is the home page, with a basic explanation of how it works and how to install and start a project using Harmonic.

![Mockup home page](http://cl.ly/image/0n3U1n0V3w2G/harmonic.png)

and this second mockup is the docs page, using the concept of cards.

![Second mockup docs page](http://cl.ly/image/2A3w421q2t3C/harmonic-docs.png)


Card Design References: 
* [http://insideintercom.io/why-cards-are-the-future-of-the-web/](http://insideintercom.io/why-cards-are-the-future-of-the-web/)
* [http://www.fastcodesign.com/1672605/how-google-unified-its-products-with-a-simple-index-card](http://www.fastcodesign.com/1672605/how-google-unified-its-products-with-a-simple-index-card)

**Comment by mateusortiz** [comment]
What do you think @jaydson?, we have to improve a lot yet.

**Comment by UltCombo** [comment]
Here's my .02

Some things that should be considered:

- **Identity.** A homepage is the identity of the product, having a subpar site affects the image of the product negatively. Designing a good visual identity is no easy task -- theme colors, fonts, spacing, behavior, the overall feel and UX are serious factors and I don't know any web designer willing to do this for free. Sure we can fork an existing boilerplate for a start, but all the mentioned concerns still apply.

- **Docs segmentation:** documentation is serious stuff. A project without documentation is as good as if it didn't exist. In some projects, over 90% of the time I spend contributing is at writing docs. Harmonic is at the early stages and rapidly evolving, thus it requires a lot of effort to keep the docs up to date. Right now, our docs are already segmented -- there's the repository's readme, and the (slightly outdated) Wiki. If we were to have a docs site, then each future change may have to be documented in up to three places. That would drain way too much time from our small group of maintainers, even more so for an early, fast-evolving project.

Don't get me wrong, a Harmonic website can be a good thing, but it also brings a lot more of responsibilities to the table.

Of course, this is just my opinion.
We shall wait until others voice their opinions as well.

//cc @jaydson @atilafassina @felipenmoura @leobalter

**Comment by mateusortiz** [comment]
Hello,
I managed to find a designer, and he makes free website design :+1:

**Comment by jaydson** [comment]
The website must be just an information page.
Docs must to be just linked and not replicated(link to Harmonic's Wiki).

@mateusortiz , we already have a designer working on Harmonic design >>> @italowaxman, please handle this with him, ok?
@robsongajunior , we need your help here to get this done.

**Comment by UltCombo** [comment]
> Docs must to be just linked and not replicated(link to Harmonic's Wiki).

Makes sense, docs should be centralized in a single place. I was wondering whether it should be in the site or in the Wiki -- the site could display the docs in a nicer format, but the Wiki allows everyone to contribute to in a far easier way.

**Comment by mateusortiz** [comment]
I am already creating a project with Italo, so I'll talk to him about the harmonic today yet :+1: 

the gulpjs.com/ linked docs in their own github

**Comment by robsongajunior** [comment]
Great, we already scheduled a call later this week to discuss about it.

**Comment by italowaxman** [comment]
Designer here! Wednesday or Thursday we can make a hangout what do you think?

**Comment by mateusortiz** [comment]
Yeap @italowaxman, mark for Wednesday or Thursday?

**Comment by italowaxman** [comment]
Thursday at 16:00, it's ok?

**Comment by mateusortiz** [comment]
@italowaxman :+1:

**Comment by robsongajunior** [comment]
@italowaxman  (Y)

**Comment by robsongajunior** [comment]
I spoke to italo, he suggested 18:00 on Friday(tomorrow).
All right for everyone?

cc/ @mateusortiz @italowaxman

**Comment by mateusortiz** [comment]
:+1:

**Comment by jaydson** [comment]
I'll close this issue, because we're currently working on this, and we have another active issue: #128
