### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/harmonic#105]
I'm trying to use async/await(es7) (experimental feature in 6to5) but i'm not sure gulp-6to5 is working.
I've changed `build.js` file:
```javascript
	config: {
		jscs: { configPath: '.jscsrc', esnext: true },
		'6to5': { blacklist: ['generators'], experimental: true },
		mocha: { bail: true, timeout: 5000 }
	}
```
My sample code:
```javascript
async function test() {
    let x = await Promise.resolve();
}
```
And i get the following error: 
`events.js:85
      throw er; // Unhandled 'error' event
            ^
/home/jaydson/Workspace/harmonic/dist/bin/parser.js:19
async function test() {
      ^^^^^^^^
SyntaxError: Unexpected token function
`  
The async function is not being transpiled.

Any thoughts @UltCombo ?

**Comment by jaydson** [comment]
I found the issue.
It seems like the config property `6to5` in `build.js` is being ignored.
I changed the `gulpfile` to this:
```javascript
.pipe(plugins['6to5'], { experimental: true })
```
instead of this:
```javascript
.pipe(plugins['6to5'], build.config['6to5'])
```
and it works.

Probably the blacklisted `generators` never were blacklisted until now.

**Comment by UltCombo** [comment]
> Probably the blacklisted generators never were blacklisted until now.

Weird. I'm pretty sure co-prompt was throwing errors when we transpiled generators.

@jaydson can you try editing `build.js` to:

```js
'6to5': { blacklist: ['generators'], whitelist: ['arrowFunctions'] },
```

And check if it works?

**Comment by UltCombo** [comment]
> Probably the blacklisted generators never were blacklisted until now.

Weird. I'm pretty sure co-prompt was throwing errors when we transpiled generators.

It looks like the async functions transform converts them to generators, so async functions transform doesn't work/is ignored when we blacklist generators. I believe this makes sense, anyway, @sebmck can you confirm?

@jaydson change the `build.js` to remove generators from the blacklist and enable experimental:

```js
'6to5': { experimental: true },
```

Does this work?

**Comment by UltCombo** [comment]
If that's the issue, then we can replace co-prompt with Inquirer then remove generators from the blacklist and use asnyc functions. :smile:

**Comment by sebmck** [comment]
Async functions and generators are transformed in the same transformer (it's delegated to regenerator). It's confusing but since 3.0.0 is going to include a [regenerator fork](https://github.com/6to5/regenerator-6to5) it'll allow it to be split up into multiple transformers.

**Comment by UltCombo** [comment]
@sebmck oh nice! Thanks for the clarification. :smile:

**Comment by jaydson** [comment]
@UltCombo both `'6to5': { experimental: true },` and `'6to5': { blacklist: ['generators'], experimental: true },` works in the same way.

**Comment by UltCombo** [comment]
@jaydson I believe `blacklist: ['generators']` disables the async transform as @sebmck explained.

Doesn't `'6to5': { experimental: true }` work? It fails to transpile async functions or throws some specific error?

**Comment by jaydson** [comment]
Oh, now i got it.
`'6to5': { experimental: true }` works (transpile async functions).
We can remove generators from the blacklist :)

**Comment by UltCombo** [comment]
Oh nice. `:)`

Btw, the whole idea behind the `build.js` file is to have project-specific settings outside of the gulpfile, so that whenever we update the gulpfile we can seamlessly copy it to the slush-es6 repository forth and back. This way we can pull updates from slush-es6 by simply copying the files over.

Of course, in the future Harmonic may need a more complex gulpfile than slush-es6's, but for the time being this workflow has been working nicely. :smiley:

**Comment by UltCombo** [comment]
@jaydson also, please test `harmonic init` before committing the changes.

IIRC, co-prompt was throwing an error when we passed a [transpiled generator](https://github.com/es6rocks/harmonic/blob/df929ae19502e5aec5dbdebada09ea56d15df6ec/src/bin/cli/util.js#L58) to it.

As we've discussed earlier, we can't transpile generators to regenerator as `co` and `co-*` libs are not transpiled (they work with native generators only). So I guess we have to drop the `co` dependency(ies) before un-blacklisting generators.

**Comment by UltCombo** [comment]
There's probably regenerator'ed versions of `co` out there, but if we're using it only for the CLI input we can easily replace it with Inquirer and drop `co`. What do you think?

**Comment by jaydson** [comment]
I think we can replace `co` and focus on `async/await`.

Weird thing is i've tested `harmonic init` and it worked well. I'm probably missing something.

**Comment by UltCombo** [comment]
@jaydson perhaps it was an issue with one of our dependencies that got fixed. Never mind it if it is working as expected for you. `:D`

> focus on `async/await`

:+1:

**Comment by jaydson** [comment]
We're already using `async functions` yay!
https://github.com/JSRocksHQ/harmonic/commit/c4bb69d0495f6b9d795b1e39075b7f919559fa6b
