### ISSUE TITLE
List ES2015(ES6)/ES2016(ES7) features Harmonic is using

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/harmonic#108]
It would be interesting/useful have a list of new ES features we're using in Harmonic.
Maybe a `markdown` file with a brief feature description and links to the lines where that feature appears.
Example:
__Named Imports__
https://github.com/es6rocks/harmonic/blob/master/src/bin/parser.js#L2

I think with this simple file we'll have a great indexed ESX resouce in the future.

**Comment by UltCombo** [comment]
Line numbers might be hard to keep updated, seeing as the source code is always changing. I'd suggest either:

- Link to specific line numbers in specific revisions, e.g. https://github.com/es6rocks/harmonic/blob/b82c1e2c5175ed2bd117d293424bf108bb7fe446/src/bin/parser.js#L2
- Link to latest revision but don't add line numbers.

**Comment by jaydson** [comment]
Well pointed.
Perhaps linking the file and put some real example is the best approach.
If the code change we can update the example if we want.

**Comment by UltCombo** [comment]
:+1:

**Comment by jaydson** [comment]
I'll close this issue. Look at the code is the best way to check Harmonic's features.

**Comment by UltCombo** [comment]
:+1:
