### ISSUE TITLE
Harmonic website content

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/harmonic#128]
# Harmonic
A static website generator built entirely with the modern JavaScript, a.k.a ES2015/ES6 ES2016/ES7

## Introduction
Harmonic is yet another JavaScript static website generator, but modern.
Harmonic's core is built using the latest JavaScript features.
By using the ECMA-262 Standard we're helping the JavaScript language to evolve and also learning how to play with.
Besides that, Harmonic actually does the "static website generator" job pretty well.

### Modern
Harmonic is built using the modern JavaScript (ES2015/ES6 - ES2016/ES7).
Take a look at the code, start learning the new JavaScript and feel free to contribute.
[Hack the code](https://github.com/es6rocks/harmonic)

### Painless blogging
As usual in a static website generator, you can focus on your content. Just write some markdown files and Harmonic will take care of everything, including pages, articles, categories and themes.
[Blogging](https://github.com/es6rocks/harmonic/wiki/Blogging)

## Easy start
You will need [Node.js](https://nodejs.org/) >= 0.10 or [io.js](https://iojs.org/en/index.html).
Harmonic is available as `npm` module:
```bash
npm install harmonic -g
```
Now you're able to buil your awesome website!
```bash
harmonic init "my_awesome_website"
cd my_awesome_website
harmonic run
# Harmonic site is running on http://localhost:9356
```

**Comment by jaydson** [comment]
//cc @UltCombo @felipenmoura @leobalter @italowaxman @robsongajunior @mateusortiz

Italo will start to work on the website layout soon, and i want to give him the content.
I wrote the text above as an initial approach.
Reviews are welcome.

@italowaxman, here some references:  
http://jekyllrb.com/
http://assemble.io/
http://www.metalsmith.io/
http://octopress.org/docs/

**Comment by UltCombo** [comment]
Nice!
A couple nitpicks:

- There seems to be a bit too much emphasis and repetition around the word "modern", perhaps we could use synonyms where possible? For instance, "Harmonic's core is built using the modern JavaScript" could be rewritten as "Harmonic's core is built using the latest JavaScript features".

- Not sure about mentioning "ECMA-262" as very few people know what it means, but the way you phrased it referring to the standard, avoiding a specific specification edition, seems good to me.

- Wording: "By using the ECMA-262 specification", I believe you can replace "specification" with "Standard" here, as all the ECMA-XXXX are referred to as [Ecma Standards](http://www.ecma-international.org/publications/standards/Stnindex.htm). E.g., from [ECMA-262](http://www.ecma-international.org/publications/standards/Ecma-262.htm):
  > ### Standard ECMA-262
  > #### *ECMAScript® Language Specification*
  > This Standard defines the ECMAScript scripting language.

- Still in the same statement from the last bullet point: "we're helping the language", seeing as very few people know what ECMA-262 means, you could be more explicit about what language we're helping: "we are helping the JavaScript language".

**Comment by italowaxman** [comment]
@jaydson @UltCombo thank you for the texts and references, now we can start creating the layout. I took a look at the references and I've had some ideas. Yesterday already I cretated a basic concept for Harmonic, I applied this on twitter https://twitter.com/harmonicjs, ever seen? What did you think?I'm planning follow something in that line.

**Comment by UltCombo** [comment]
Nice work, perhaps a bit more of contrast would be nice.

**Comment by italowaxman** [comment]
The idea of applying the brand this way was intentional, from a concept of a technology of the future with "transparency" effect. The spotlight will represent something new and extreme fucking god solution ;)

**Comment by UltCombo** [comment]
Yes, I like the concept, I only meant that it is actually a bit hard to read on my screen.
Perhaps it would be possible to add a bit of contrast while keeping the transparency concept? I'd just like to make it a bit more accessible/easier to read. :smiley:

**Comment by italowaxman** [comment]
Nice, I will make this change at night. Let's think about accessibility forever.

**Comment by jaydson** [comment]
Thanks @UltCombo. All suggestions were applied.

**Comment by italowaxman** [comment]
Now, I Present to you the new site Harmonic.
I tried to do something unique and completely different from what I saw out there, I also had the idea of "recruit" contributors to the project. I also tried to simplify the space of information avoiding a long and tedious scrolling.
What did you think?

![harmonic_v1](https://cloud.githubusercontent.com/assets/2953435/6882854/75cb77be-d572-11e4-8e3d-9a43bccc6e10.jpg)

**Comment by jaydson** [comment]
Holy shit, that's simply awesome.

**Comment by UltCombo** [comment]
> Holy shit, that's simply awesome.

I fully agree. :smile:

**Comment by italowaxman** [comment]
I'm very happy. Let's Rock!
I tried to really do something a little different from normal to have personality.
Now is to start the front-end to launch in time for the JS Conf Yi.

**Comment by jaydson** [comment]
Little text changes:

"We want you dev" => "We want you"
"Contributions are very welcome" => "If you're a JavaScript hacker, help us!"
"Very easy start" => "Easy to start"
"Now, enter in your website...." => "Now you're ready to go"
"See the Harmonic in action" = "Harmonic in action"
"The website is already online ES6Rocks.com"

In the "in action" section we can structure like this:
## Harmonic in action
[es6ocks.com](es6ocks.com) - A collaborative website about the ECMAScript sixth edition, a.k.a. ES6
[jaydson.org](jaydson.org) - Harmonic maintainer personal website
[harmonicjs.com](harmonicjs.com) - Harmonic website itself  

Are you using Harmonic? [Let us know!](https://github.com/es6rocks/harmonic/issues)

**Comment by jaydson** [comment]
BTW, http://harmonicjs.com/ is live!

The project is here: https://github.com/es6rocks/harmonic-website

@italowaxman talk with me before start coding, so i can help with the skeleton.

**Comment by italowaxman** [comment]
After text changes, its a new layout version. What you think?
@jaydson lets start the code this week ok?

![harmonic_v2](https://cloud.githubusercontent.com/assets/2953435/6888657/5b4a83c8-d65b-11e4-85fd-f208902a5363.jpg)

**Comment by jaydson** [comment]
Awesome @italowaxman 

Little things:
I forget that phrase: "The website is already online ES6Rocks.com"
I think you can just remove it.
The last one, can you find a way to add a section about Harmonic being cross-platform (Linux, Windows, Mac)?

Let's start code!

**Comment by robsongajunior** [comment]
Really awesome, Good job  @italowaxman .
Go Go Let's start *---*

**Comment by italowaxman** [comment]
Thanks for all feedback, i'm very excited with this project. It's link of all the project archives in my dropbox. Any questions?

https://www.dropbox.com/s/i33f3hgyxpcukob/harmonic.zip?dl=0

**Comment by robsongajunior** [comment]
Thanks @italowaxman.
I will go to  talk with Mateus Ortiz, so let's start code.

: D

**Comment by jaydson** [comment]
ping @robsongajunior @mateusortiz

**Comment by robsongajunior** [comment]
@jaydson pong!

I will finish template structure this week and I open a PR!
With this, we can start the code .

**Comment by jaydson** [comment]
:+1:

**Comment by viniciusdacal** [comment]
Any news about the website? If you guys need, I would like to help.

**Comment by jaydson** [comment]
That's awesome you want to help @viniciusdacal !
I know @robsongajunior is working on it, but you can help us to put this live soon.

@robsongajunior what we still need to finish the website?

**Comment by jaydson** [comment]
Hey @viniciusdacal , @robsongajunior os working on the website here: https://github.com/JSRocksHQ/harmonic-theme-selfblog

**Comment by viniciusdacal** [comment]
@jaydson thanks, I'm going to check there.

**Comment by UltCombo** [comment]
Seeing as the site is already live, can we close this issue? @jaydson

**Comment by jaydson** [comment]
Sure! Thanks @UltCombo
