### ISSUE TITLE
Deprecation warning: moment.lang is deprecated. Use moment.locale instead.

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#134]
This annoying message originates from [`strings-parser-date`](https://github.com/assemble/strings-parser-date) which is a dependency of `permalinks`.

**Comment by UltCombo** [comment]
https://github.com/assemble/strings-parser-date/issues/1

**Comment by brenopolanski** [comment]
I'm with this problem too :\

**Comment by UltCombo** [comment]
It is just a warning -- a really ugly one, but doesn't affect functionality at all.
The ways to fix it would be:

- Fix the root of the problem -- https://github.com/assemble/strings-parser-date/issues/1
- Send a patch to [permalinks repo](https://github.com/jonschlinkert/permalinks) to no longer depend on `strings-parser-date` -- https://github.com/jonschlinkert/permalinks/issues/1
- Replace Harmonic's `permalinks` dependency with a similar package.

I didn't give this much priority yet as the warning doesn't affect functionality, but it is rather annoying to see it on every startup.

**Comment by UltCombo** [comment]
Fixed by https://github.com/assemble/strings-parser-date/commit/ecb53fa33dd63ea5a283734374de1efbeb37a696.

**Comment by jaydson** [comment]
:sunglasses:
