### ISSUE TITLE
Recipe to improve theme development workflow

### ISSUE THREAD

**Issue by gpedro** [JSRocksHQ/harmonic#145]
Hi, 
I'm developing and fixing some themes for Harmonic and i felt a slowness in development caused by boring workflow Harmonic. So I created this Gulpfile to improve workflow.

> https://gist.github.com/gpedro/dbac96c39028e949d68b

**Comment by UltCombo** [comment]
Nice!
I think I can merge this into #118 and ship a single watch/live reload task that works for posts, resources and the current template.

**Comment by UltCombo** [comment]
Now natively supported in Harmonic@0.4

**Comment by gpedro** [comment]
thanks! 0/
