### ISSUE TITLE
Dynamic template pages

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/harmonic#164]
Harmonic's current implementation work with just 3 template files: `index.html`, `post.html`, `page.html` and `tags_archives.html`.  
This is fine for a simple blog, but for a dynamic web site, this is not  very useful.

What I mean is we need a better way to handle various page templates, not just the current ones.
Also, this must to be dynamic, if I want a new page template, I want to create it by myself, and Harmonic should take care of the rest.

Use case:
I'm working on my blog, and I want to have 2 different pages.
Each page have different structures, different HTML, etc.
By having this feature, I'll be able to create as many pages I want, with different templates.

I need some feedbacks here: @UltCombo @felipenmoura @viniciusdacal

**Comment by viniciusdacal** [comment]
currently it's static what template we use to generate pages:
```
pageTpl = this.theme.getFileContents('page.html'),
```
maybe we could just read an atribute `layout` inside md files and use it to decide what template we should use to render the page.

Actually, we already have this attribute inside md files by default
```
<!--
layout: page
```

**Comment by viniciusdacal** [comment]
And, we could have a way to create more html pages inside theme, working the same way as index.html, which we render just with `config` and `metadata`.

**Comment by UltCombo** [comment]
> maybe we could just read an atribute layout inside md files and use it to decide what template we should use to render the page.

:+1:

So, `post`, `page`, `index` and `tag_archives` are built-in (required, customizable) templates, and you can create new ones by placing `.html` files inside the theme package. And to create a new page, run `harmonic new_page` and change the `template` markdown metadata to the name of the template file (without the `.html` extension).

What do you guys think? I believe it can't get much simpler than this. Later on, we can add a template prompt to the `harmonic new_page` CLI.

**Comment by jaydson** [comment]
That's a great idea guys!
I'll try to make this when I have a free time.
Please let me know if one of you want to start something.

**Comment by viniciusdacal** [comment]
@jaydson did you start something? I think I'll have a free time today.

**Comment by jaydson** [comment]
Nope, not yet.
Feel free to start :+1:

**Comment by UltCombo** [comment]
Fixed by #170.

**Comment by jaydson** [comment]
This was never released?

**Comment by UltCombo** [comment]
@jaydson That's true. If I recall correctly, the release was pending an Wiki update and changelog.

By the way, I'm proposing #181 in order to improve the way we maintain documentation and avoid cases such as this.

**Comment by jaydson** [comment]
:cry: 
I was trying to build something yesterday and noticed it was missing.

I'll check #181.

Thanks @UltCombo
