### ISSUE TITLE
pages variable haas all pages instead having just english pages or portuguese pages

### ISSUE THREAD

**Issue by viniciusdacal** [JSRocksHQ/harmonic#166]
Inside index.html, when we try to access variable `posts`, we got posts from a specific language.
With recently changes in pages, we added support for multiple language, but we didn't change var `pages` structure, so we are receiving all pages inside index template. 
How about we change it's structure to be equal var `posts`.

Above that, I did notice we can't access var `pages` inside pages template.
If I want to create a menu using var `pages` to list my available pages,  that appears in all pages, It's not possible.
Please, correct if I'm wrong.

 @UltCombo @jaydson

**Comment by UltCombo** [comment]
How about we change it's structure to be equal var posts.

:+1: 

Above that, I did notice we can't access var pages inside pages template.

See #161

**Comment by viniciusdacal** [comment]
Thanks @UltCombo 
I will work on var `pages` structure, and I'll send a pull request soon.
After that, I'll try to figure out something about #161, because I need that to migrate my blog.
