### ISSUE TITLE
`metadata.default_lang` is reversed

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#169]
Why is the [`default_lang`](https://github.com/JSRocksHQ/harmonic/blob/c407fc6424eba447e8cdc08fc46d4ef8b2ec7f2a/src/bin/parser.js#L264) metadata property representing the opposite of whether the post is in the default lang?
Any ideas, @jaydson?

Fixing this will break all existing themes that rely on it.
I propose adding a new property, `metadata.isDefaultLang` implementing the correct behavior, and deprecate or outright remove `metadata.default_lang`.

What do you guys think?

**Comment by jaydson** [comment]
I think this `default_lang` was used to check if there's a default lang, not to check if the post is the default lang.
Perhaps it can be changed and there's no need for it anymore.
