### ISSUE TITLE
ESLint config: use the "nofunc" additional option in `no-use-before-define`

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#172]
This has caused quite a few refactoring hazards as seen [here](https://github.com/JSRocksHQ/harmonic/pull/162/files#r34251268).

We should add the `"nofunc"` option to the [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define) rule config in order to ignore function declarations. 

What do you guys think?

/cc @viniciusdacal @jaydson

**Comment by UltCombo** [comment]
What I mean is, we should add the `"nofunc"` option to the [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define) rule config in order to ignore function declarations. 
What do you guys think?

**Comment by viniciusdacal** [comment]
Yeah, I think it's a great idea :smile: . As you said before, a function it's available in the entire scope.
I don't think that's is a bad practice, if we look for some "clean code" practices, like the "The Step- down Rule", that kind of situation will happen always.

**Comment by UltCombo** [comment]
:sweat_smile: This somehow fell off my radar, fixed now.
