### ISSUE TITLE
Migrate documentation to inside the repository

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#181]
I'm considering to migrate the docs from the Wiki to inside the main repository.

Sindre Sorhus has laid some [interesting points](https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4) for this. I believe the main point is that having the docs inside the repository would enable us to update the documentation and review it in the same pull requests that add or modify behavior, thus making it much easier to update and maintain the docs.

What do you think?

**Comment by jaydson** [comment]
Totally agree.
Let's go forward with this.

**Comment by UltCombo** [comment]
Great. :)

My plan is:
- Clone the Wiki repository (https://github.com/JSRocksHQ/harmonic.wiki.git) and put its contents in a `doc` directory, fixing relative links as needed.
- Edit the Wiki pages to link to the main repository's `doc` directory and lock down the Wiki to contributors only, in order to avoid misplaced contributions from the public that would be missed.

**Comment by jaydson** [comment]
That's sounds like a good plan :+1:

**Comment by jaydson** [comment]
:sunglasses:

**Comment by UltCombo** [comment]
I'll update the Wiki pages to link to the new docs after fixing the P1 issues.

**Comment by UltCombo** [comment]
The Wiki now links to the Harmonic repository's docs.

**Comment by jaydson** [comment]
Awesome, thanks @UltCombo !

**Comment by UltCombo** [comment]
Yay, new docs!

![](http://i.giphy.com/LkjlH3rVETgsg.gif)
