### ISSUE TITLE
Feature to change post language

### ISSUE THREAD

**Issue by ftonato** [JSRocksHQ/harmonic#187]
I suggest creating a feature to change or select the language of the post I'm reading.

Then in each post show an option to translate to other available languages, so the user does not need to change the blog's language and access the post again.

**Comment by UltCombo** [comment]
In the Harmonic side, when rendering posts and pages we can add a new template data variable such as `postTranslations`, `fileTranslations`, `availableTranslations` or just `translations`. This would be an array of language names that contain a file with the same name as the current one.

Then we can think about implementing an UI in the `harmonic-theme-jsrocks`. :smiley:

**Comment by ftonato** [comment]
I'm closing outdated issues and pull-requests that are no longer relevant given how much time has passed since they were opened.
