### ISSUE TITLE
Support browser-sync?

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#49]
I see @jaydson has been working on the `watch` branch which, as far as I can see, regenerates the whole site when files are edited.

I believe it'd be optimal if we could refresh the browser after the new files are generated.

As far as I know, [BrowserSync](http://www.browsersync.io/) is the simplest way to achieve this. It does not require any browser plugins nor any modification to the pages.

BrowserSync has 2 operation modes: it can create a static server or proxy an existing server. In either case, it will automatically inject the necessary scripts to communicate with Node.

In our case, I believe we could replace the `node-static` dependency with BrowserSync's static server, and in watch mode we just have to add `browserSync.reload` to the end of the site regenerating pipeline.

And if we replace node-static with [browser-sync](https://github.com/shakyshane/browser-sync), it may as well be better to have watch mode enabled by default to keep the logic simple.

Thoughts?

**Comment by jaydson** [comment]
Did you had time to test it?
This still a great feature :)

**Comment by UltCombo** [comment]
Oh my bad, I ended up without time to test it back then.
This is still a great idea, I'll probably try to implement it this weekend.
I intend to finish writing the [TDZ post](https://github.com/es6rocks/es6rocks.github.io/blob/tdz/src/posts/en/temporal-dead-zone-tdz.md) and publish a stable slush-es6 version ASAP, then I'll have time to go through these Harmonic issues.

**Comment by jaydson** [comment]
:+1:

**Comment by UltCombo** [comment]
I was about to propose a `--no-cache`/`--dev` flag to `harmonic run` to aid writing articles, but then I just realized that implementing browser-sync would make such feature redundant hah.

I still have some more stuff to do around GitHub, but once I get back to Harmonic, browser-sync will be a top priority.

**Comment by UltCombo** [comment]
I've imported the [priority labels](https://github.com/jshint/jshint/labels) from JSHint, by the way.

**Comment by jaydson** [comment]
Thanks @UltCombo .
The labels "good first bug" and "Proposal" ire great, we can also use it.

**Comment by UltCombo** [comment]
@jaydson agreed, feel free to add them. `=]`

BTW, I haven't got to work on browser-sync implementation yet as I have some slightly late projects/tasks -- I said I'd help on gulp-jscs reporters about [a month ago](https://github.com/jscs-dev/gulp-jscs/pull/57#issuecomment-68585387) and just got to it now heh.

**Comment by UltCombo** [comment]
I believe we can deploy Harmonic 0.0.10 after implementing browser-sync, I guess this will be the main feature of the release then. It would be nice to have a changelog (#116) to know the releases' details.

**Comment by jaydson** [comment]
Seems good to me.

**Comment by jaydson** [comment]
![](http://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy.gif)

**Comment by UltCombo** [comment]
![](http://giant.gfycat.com/TediousBriskCreature.gif)
