### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by jaydson** [JSRocksHQ/harmonic#65]
Create a basic default theme the for harmonic.
Today, we have the ES6Rocks theme by default, that's not good.
We need a basic theme with some info about Harmonic, docs, etc.

**Comment by UltCombo** [comment]
Never mind pages, I guess those can be linked manually as ES6 Rocks does at the moment. Anyway, those are not a priority.

**Comment by UltCombo** [comment]
Has anyone started working on this? Otherwise, let's remove the milestone as to not block the next release.

**Comment by jaydson** [comment]
:+1:

**Comment by UltCombo** [comment]
We now have a default "blank" theme.

But I wonder if we could make it less "blank"? Currently, the default theme has no styling whatsoever, which is really ugly and causes a terrible first impression (imo).

I believe the ideal would be to have a basic and neutral theme (preferably unrelated to JSRocks).

If anything, back when we used to ship Harmonic with the old ES6 Rocks theme, upon running `harmonic run` the user would immediately get the impression "This works!", and now it is more like "meh, this is shit.", in my humble opinion.

// cc @jaydson @atilafassina

**Comment by jaydson** [comment]
You're totally right.
We need to spend some time building this default-theme, at least we must have a theme that doesn't sucks like we have now.

**Comment by UltCombo** [comment]
Fixed by https://github.com/JSRocksHQ/harmonic-theme-default/commit/9cbd0fc5aabfbcdb95b1acc667aa6e9816a22ef4
