### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by atilafassina** [JSRocksHQ/harmonic#69]
There's already support for Stylus and LESS, it would make sense to support natively also SASS.

Currently SASS has 2 compilers:

- [LibSASS](http://libsass.org/) - a C++ compiler that is also supported fully with [Node-SASS](https://github.com/sass/node-sass)
- [SASS](http://sass-lang.com/) - the original compiler, where features land first and has bigger community support

To add SASS support, would make sense to simply run the **gem** compiler through the terminal and let Ruby/SASS dependencies for the user to take care.

Therefore, full SASS support would have 2 categories, actually: **SASS** and **LibSASS**

**Comment by jaydson** [comment]
This is too old and we'll not support SASS, so I'll close it.

**Comment by UltCombo** [comment]
Sass can be supported through plugins, once we implement the plugins architecture (#140).

**Comment by jaydson** [comment]
Yep, that's true. But it makes sense to keep this issue closed, right?
Maybe we can focus on Sass support in the future.

**Comment by UltCombo** [comment]
> Yep, that's true. But it makes sense to keep this issue closed, right?

Yeah, sure—it does not belong in the core, and the plugin(s) (Ruby Sass, node-sass) can even be made by the community in the future.

**Comment by jaydson** [comment]
:+1:
