### ISSUE TITLE
Harmonic templates

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#70]
As per #69 discussion, the default template will only be maintained in Stylus.

Right now, we have a second template in this repository which is a rewrite of the default template in LESS by @robsonaraujojunior. The idea is to relocate this template (and the new templates that will be written in the future) to a "template library".

I believe we can create a "harmonic-templates" repository for these, so that the main Harmonic repository does not get littered with issues/PRs regarding outdated templates.

This issue is to discuss how we can best implement this strategy.

**Comment by jaydson** [comment]
![screenshot from 2015-02-02 22 45 17](https://cloud.githubusercontent.com/assets/72206/6012278/5c2533e6-ab2d-11e4-9fa5-442d7f5180a8.png)
This really annoys me;
Harmonic is JavaScript project. 100% JavaScript.
But we still have CSS in our codebase, because templates are still in the same repo.
I think i'll prioritize the decoupling.

**Comment by UltCombo** [comment]
@jaydson sounds like a good idea to me. `=]`

**Comment by jaydson** [comment]
I've started to work on this feature.
The branch was already pushed to the origin: `themes`.

What this branch introduces:
### Themes as npm modules
- Yes :sparkling_heart: 
- Themes by convention are prefixed as `harmonic-theme-`.
- Harmonic's default theme is already published => https://www.npmjs.com/package/harmonic-theme-default
- Harmonic default theme on Github => https://github.com/es6rocks/harmonic-theme-default

### Clean-up Harmonic
- `templates` folder was removed from the core
- Unnecessary `img` folder was removed

### Changes in Harmonic code-base
- Look for the `npm_modules` + THEME_NAME (configured in harmonic.json file) instead `src/templates`
- Added `package.json` to the skeleton with pre-defined `harmonic-theme-default` as dependency

### How it works
Harmonic themes are npm modules, you must to install one before start build your website.
If you started a new Harmonic project, the default theme is already in the project dependencies list, so you must to run `npm install` before run Harmonic.
If you want to build your own theme, you can just install it via `npm` as well, pointing to your local files:
```bash
npm install ../harmonic-theme-my-awesome-theme
```
But we encourage you to publish it on npm (with the prefix `harmonic-theme`).

### TODO
- Throw a friendly error if a template was not found
- Refactor unit tests that are failing 

### How to test this branch
```bash
git fetch
git checkout themes
gulp
```
Start a new Harmonic project:
```bash
harmonic init "testing-themes"
cd testing-themes
npm install // Should install the default theme
harmonic run
```

//cc @UltCombo @felipenmoura @leobalter @jcemer @robsongajunior 
Review needed.

**Comment by UltCombo** [comment]
Woah, so much awesomeness!
I don't have much time to test right now, but a small improvement idea: we could run `npm install` automatically after `harmonic init`. The [`gulp-install` package](https://github.com/slushjs/gulp-install) comes to mind, there should be non-gulp alternatives as well.

**Comment by jaydson** [comment]
That's a good idea @UltCombo

**Comment by jaydson** [comment]
https://github.com/JSRocksHQ/harmonic/releases/tag/v0.1.0
