### ISSUE TITLE
i18n Pages

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/harmonic#73]
Currently, `harmonic new_page` correctly generates a new markdown file inside each `src/pages/[lang]`, but `harmonic build` will only output a single rendered version. It looks like all languages are being written to the same location and overwrite each other.

That is, the pages are written to `public/pages/[slug]/index.html` when it should be `public/pages/[lang]/[slug]/index.html`.

Also, shouldn't there be some kind of listing/indexing of pages? Or is the user supposed to link to them in the layout manually?

**Comment by viniciusdacal** [comment]
@UltCombo Any news about this issue?

**Comment by UltCombo** [comment]
@viniciusdacal well, Jaydson has proposed a fix for this in #97 but there were a few issues and that PR is obsolete now. It shouldn't be too hard to fix though.

**Comment by jaydson** [comment]
This issue was lost in time.
![](http://static.tumblr.com/7bbb50d6e97eccd7f1c8266ced7e7763/kovghdw/Eoxmzzar3/tumblr_static_lostintime.jpg)
But @UltCombo is right, it's simple to fix it.
I can do it soon, but you're welcome to try @viniciusdacal :)

**Comment by jaydson** [comment]
\o/
